::Cleaning Default Favorites
IF EXIST "%SYSTEMROOT%\favorites\channels" RD /S /Q "%SYSTEMROOT%\favorites\channels"> nul
IF EXIST "%SYSTEMROOT%\favorites\dell" RD /S /Q "%SYSTEMROOT%\favorites\dell"> nul
IF EXIST "%SYSTEMROOT%\favorites\freeserve channels" RD /S /Q "%SYSTEMROOT%\favorites\freeserve channels"> nul
IF EXIST "%SYSTEMROOT%\favorites\media" RD /S /Q "%SYSTEMROOT%\favorites\media"> nul
IF EXIST "%SYSTEMROOT%\favorites\About Freeserve.url" DEL /F /A "%SYSTEMROOT%\favorites\About Freeserve.url"
IF EXIST "%SYSTEMROOT%\favorites\Auctions.url" DEL /F /A "%SYSTEMROOT%\favorites\Auctions.url"
IF EXIST "%SYSTEMROOT%\favorites\Chat.url" DEL /F /A "%SYSTEMROOT%\favorites\Chat.url"
IF EXIST "%SYSTEMROOT%\favorites\email.url" DEL /F /A "%SYSTEMROOT%\favorites\email.url"
IF EXIST "%SYSTEMROOT%\favorites\Freeserve.url" DEL /F /A "%SYSTEMROOT%\favorites\Freeserve.url"
IF EXIST "%SYSTEMROOT%\favorites\Freeserve Online Help.url" DEL /F /A "%SYSTEMROOT%\favorites\Freeserve Online Help.url"
IF EXIST "%SYSTEMROOT%\favorites\msn.url" DEL /F /A "%SYSTEMROOT%\favorites\msn.url"
IF EXIST "%SYSTEMROOT%\favorites\msncom~1.url" DEL /F /A "%SYSTEMROOT%\favorites\msncom~1.url"
IF EXIST "%SYSTEMROOT%\favorites\Radio Station Guide.url" DEL /F /A "%SYSTEMROOT%\favorites\Radio Station Guide.url"
IF EXIST "%SYSTEMROOT%\favorites\Search.url" DEL /F /A "%SYSTEMROOT%\favorites\Search.url"
IF EXIST "%SYSTEMROOT%\favorites\web events.url" DEL /F /A "%SYSTEMROOT%\favorites\web events.url"
IF EXIST "%SYSTEMROOT%\favorites\links\About Freeserve.url" DEL /F /A "%SYSTEMROOT%\favorites\links\About Freeserve.url"
IF EXIST "%SYSTEMROOT%\favorites\links\Auctions.url" DEL /F /A "%SYSTEMROOT%\favorites\links\Auctions.url"
IF EXIST "%SYSTEMROOT%\favorites\links\Best of the Web.url" DEL /F /A "%SYSTEMROOT%\favorites\links\Best of the Web.url"
IF EXIST "%SYSTEMROOT%\favorites\links\Channel Guide.url" DEL /F /A "%SYSTEMROOT%\favorites\links\Channel Guide.url"
IF EXIST "%SYSTEMROOT%\favorites\links\Chat.url" DEL /F /A "%SYSTEMROOT%\favorites\links\Chat.url"
IF EXIST "%SYSTEMROOT%\favorites\links\Customize Links.url" DEL /F /A "%SYSTEMROOT%\favorites\links\Customize Links.url"
IF EXIST "%SYSTEMROOT%\favorites\links\Email.url" DEL /F /A "%SYSTEMROOT%\favorites\links\Email.url"
IF EXIST "%SYSTEMROOT%\favorites\links\Free Hotmail.url" DEL /F /A "%SYSTEMROOT%\favorites\links\Free Hotmail.url"
IF EXIST "%SYSTEMROOT%\favorites\links\Freeserve" DEL /F /A "%SYSTEMROOT%\favorites\links\Freeserve.url"
IF EXIST "%SYSTEMROOT%\favorites\links\Freese~1.url" DEL /F /A "%SYSTEMROOT%\favorites\links\Freeserve Online Help.url"
IF EXIST "%SYSTEMROOT%\favorites\links\Internet Start.url" DEL /F /A "%SYSTEMROOT%\favorites\links\Internet Start.url"
IF EXIST "%SYSTEMROOT%\favorites\links\Microsoft.url" DEL /F /A "%SYSTEMROOT%\favorites\links\Microsoft.url"
IF EXIST "%SYSTEMROOT%\favorites\links\Search.url" DEL /F /A "%SYSTEMROOT%\favorites\links\Search.url"
IF EXIST "%SYSTEMROOT%\favorites\links\Windows Media.url" DEL /F /A "%SYSTEMROOT%\favorites\links\Windows Media.url"
IF EXIST "%SYSTEMROOT%\favorites\links\Windows.url" DEL /F /A "%SYSTEMROOT%\favorites\links\Windows.url"
IF EXIST "%SYSTEMROOT%\favorites\links\Windows Update.url" DEL /F /A "%SYSTEMROOT%\favorites\links\Windows Update.url"

::Cleaning Default Favourites from the users profile
IF EXIST "%USERPROFILE%\favorites\channels\nul" RD /S /Q "%USERPROFILE%\favorites\channels"> nul
IF EXIST "%USERPROFILE%\favorites\dell\nul" RD /S /Q "%USERPROFILE%\favorites\dell"> nul
IF EXIST "%USERPROFILE%\favorites\freese~1\nul" RD /S /Q "%USERPROFILE%\favorites\freeserve channels"> nul
IF EXIST "%USERPROFILE%\favorites\media\nul" RD /S /Q "%USERPROFILE%\favorites\media"> nul
IF EXIST "%USERPROFILE%\favorites\About Freeserve.url" DEL /F /A "%USERPROFILE%\favorites\About Freeserve.url"
IF EXIST "%USERPROFILE%\favorites\Auctions.url" DEL /F /A "%USERPROFILE%\favorites\Auctions.url"
IF EXIST "%USERPROFILE%\favorites\Chat.url" DEL /F /A "%USERPROFILE%\favorites\Chat.url"
IF EXIST "%USERPROFILE%\favorites\email.url" DEL /F /A "%USERPROFILE%\favorites\email.url"
IF EXIST "%USERPROFILE%\favorites\Freeserve.url" DEL /F /A "%USERPROFILE%\favorites\Freeserve.url"
IF EXIST "%USERPROFILE%\favorites\Freeserve Online Help.url" DEL /F /A "%USERPROFILE%\favorites\Freeserve Online Help.url"
IF EXIST "%USERPROFILE%\favorites\msn.url" DEL /F /A "%USERPROFILE%\favorites\msn.url"
IF EXIST "%USERPROFILE%\favorites\msncom~1.url" DEL /F /A "%USERPROFILE%\favorites\msncom~1.url"
IF EXIST "%USERPROFILE%\favorites\Radio Station Guide.url" DEL /F /A "%USERPROFILE%\favorites\Radio Station Guide.url"
IF EXIST "%USERPROFILE%\favorites\Search.url" DEL /F /A "%USERPROFILE%\favorites\Search.url"
IF EXIST "%USERPROFILE%\favorites\web events.url" DEL /F /A "%USERPROFILE%\favorites\web events.url"
IF EXIST "%USERPROFILE%\favorites\links\About Freeserve.url" DEL /F /A "%USERPROFILE%\favorites\links\About Freeserve.url"
IF EXIST "%USERPROFILE%\favorites\links\Auctions.url" DEL /F /A "%USERPROFILE%\favorites\links\Auctions.url"
IF EXIST "%USERPROFILE%\favorites\links\Best of the Web.url" DEL /F /A "%USERPROFILE%\favorites\links\Best of the Web.url"
IF EXIST "%USERPROFILE%\favorites\links\Channel Guide.url" DEL /F /A "%USERPROFILE%\favorites\links\Channel Guide.url"
IF EXIST "%USERPROFILE%\favorites\links\Chat.url" DEL /F /A "%USERPROFILE%\favorites\links\Chat.url"
IF EXIST "%USERPROFILE%\favorites\links\Customize Links.url" DEL /F /A "%USERPROFILE%\favorites\links\Customize Links.url"
IF EXIST "%USERPROFILE%\favorites\links\Email.url" DEL /F /A "%USERPROFILE%\favorites\links\Email.url"
IF EXIST "%USERPROFILE%\favorites\links\Free Hotmail.url" DEL /F /A "%USERPROFILE%\favorites\links\Free Hotmail.url"
IF EXIST "%USERPROFILE%\favorites\links\Freeserve" DEL /F /A "%USERPROFILE%\favorites\links\Freeserve.url"
IF EXIST "%USERPROFILE%\favorites\links\Freese~1.url" DEL /F /A "%USERPROFILE%\favorites\links\Freeserve Online Help.url"
IF EXIST "%USERPROFILE%\favorites\links\Internet Start.url" DEL /F /A "%USERPROFILE%\favorites\links\Internet Start.url"
IF EXIST "%USERPROFILE%\favorites\links\Microsoft.url" DEL /F /A "%USERPROFILE%\favorites\links\Microsoft.url"
IF EXIST "%USERPROFILE%\favorites\links\Search.url" DEL /F /A "%USERPROFILE%\favorites\links\Search.url"
IF EXIST "%USERPROFILE%\favorites\links\Windows Media.url" DEL /F /A "%USERPROFILE%\favorites\links\Windows Media.url"
IF EXIST "%USERPROFILE%\favorites\links\Windows.url" DEL /F /A "%USERPROFILE%\favorites\links\Windows.url"
IF EXIST "%USERPROFILE%\favorites\links\Windows Update.url" DEL /F /A "%USERPROFILE%\favorites\links\Windows Update.url"

::Cleaning Default Favourites from default users profile
IF EXIST "%SYSTEMDRIVE%\docume~1\defaul~1\favori~1\media" RD /S /Q "%SYSTEMDRIVE%\docume~1\defaul~1\favori~1\media"> nul

::Cleaning Default Graphic files from Windows (they are useless)
IF EXIST "%SYSTEMROOT%\blue lace 16.bmp" DEL /F /A "%SYSTEMROOT%\blue lace 16.bmp"
IF EXIST "%SYSTEMROOT%\coffee bean.bmp" DEL /F /A "%SYSTEMROOT%\coffee bean.bmp"
IF EXIST "%SYSTEMROOT%\feathertexture.bmp" DEL /F /A "%SYSTEMROOT%\feathertexture.bmp"
IF EXIST "%SYSTEMROOT%\gone fishing.bmp" DEL /F /A "%SYSTEMROOT%\gone fishing.bmp"
IF EXIST "%SYSTEMROOT%\greenstone.bmp" DEL /F /A "%SYSTEMROOT%\greenstone.bmp"
IF EXIST "%SYSTEMROOT%\prairie wind.bmp" DEL /F /A "%SYSTEMROOT%\prairie wind.bmp"
IF EXIST "%SYSTEMROOT%\rhododendron.bmp" DEL /F /A "%SYSTEMROOT%\rhododendron.bmp"
IF EXIST "%SYSTEMROOT%\river sumida.bmp" DEL /F /A "%SYSTEMROOT%\river sumida.bmp"
IF EXIST "%SYSTEMROOT%\santa fe stucco.bmp" DEL /F /A "%SYSTEMROOT%\santa fe stucco.bmp"
IF EXIST "%SYSTEMROOT%\soap bubbles.bmp" DEL /F /A "%SYSTEMROOT%\soap bubbles.bmp"
IF EXIST "%SYSTEMROOT%\zapotec.bmp" DEL /F /A "%SYSTEMROOT%\zapotec.bmp"

::Cleaning media default from shared documents
IF EXIST "%SYSTEMDRIVE%\docume~1\alluse~1\docume~1\my music\music.asx" DEL /F /A "%SYSTEMDRIVE%\docume~1\alluse~1\docume~1\my music\music.asx"
IF EXIST "%SYSTEMDRIVE%\docume~1\alluse~1\docume~1\my music\music.bmp" DEL /F /A "%SYSTEMDRIVE%\docume~1\alluse~1\docume~1\my music\music.bmp"
IF EXIST "%SYSTEMDRIVE%\docume~1\alluse~1\docume~1\my music\music.wma" DEL /F /A "%SYSTEMDRIVE%\docume~1\alluse~1\docume~1\my music\music.wma"

::Cleaning media sample files from shared documents
IF EXIST "%SYSTEMDRIVE%\docume~1\alluse~1\docume~1\my music\sample~1" RD /S /Q "%SYSTEMDRIVE%\docume~1\alluse~1\docume~1\my music\sample~1"> nul

::Cleaning useless shortcuts on desktop
IF EXIST "%SYSTEMROOT%\desktop\online services" RD /S /Q "%SYSTEMROOT%\desktop\online services"> nul
IF EXIST "%SYSTEMROOT%\desktop\windows media player.lnk" DEL /F /A "%SYSTEMROOT%\desktop\windows media player.lnk"> nul
IF EXIST "%SYSTEMROOT%\desktop\connec~1.lnk" DEL /F /A "%SYSTEMROOT%\desktop\connec~1.lnk"

::Cleaning shortcuts for online services on your desktop
IF EXIST "%USERPROFILE%\desktop\online services" RD /S /Q "%USERPROFILE%\desktop\online services"> nul
IF EXIST "%USERPROFILE%\desktop\windows media player.lnk" DEL /F /A "%USERPROFILE%\desktop\windows media player.lnk"> nul
IF EXIST "%USERPROFILE%\desktop\connec~1.lnk" DEL /F /A "%USERPROFILE%\desktop\connec~1.lnk"> nul

::Cleaning stationery
IF EXIST "%PROGRAMFILES%\common~1\micros~1\stationery" RD /S /Q "%PROGRAMFILES%\common~1\micros~1\stationery"> nul

ECHO REGEDIT4> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO ;  cleanup of mru programs history in registry>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Adobe\Acrobat Reader\5.0\AVGeneral\cRecentFiles]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Adobe\Acrobat\5.0\Weblink\5.0\OpenURL]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_LOCAL_MACHINE\Software\Adaptec\Audio_CD_Info]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\JASC\Animation Shop\FileOpenDialog]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\JASC\Animation Shop\FileSaveDialog]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\JASC\Animation Shop\SaveAsDialog]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\JASC\Animation Shop\Recent File List]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Babylon\Babylon Translator\Users\Default\History]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Babylon\Babylon Translator\WebSearch]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Babylon\Babylon Translator\Users\Default\WebSearch]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_USERS\.Default\Software\Babylon\Babylon Translator\Users\Default\History]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_USERS\.Default\Software\Babylon\Babylon Translator\Users\Default\WebSearch]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_USERS\.Default\Software\Babylon\Babylon Translator\WebSearch]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Van Dyke Technologies\CRT\Recent File List]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_USERS\.DEFAULT\Software\GlobalSCAPE\CuteFTP 4.0\Cute MP3 and File Finder\Keywords]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_USERS\.DEFAULT\Software\GlobalSCAPE\CuteFTP 3.0\Cute MP3 and File Finder\Keywords]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\GlobalSCAPE\CuteFTP 3.0\Cute MP3 and File Finder\Keywords]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\GlobalSCAPE\CuteFTP 4.0\Cute MP3 and File Finder\Keywords]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\GlobalSCAPE\CuteMX\SearchInfo]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_USERS\.DEFAULT\Software\GlobalSCAPE\CuteMX\SearchInfo]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\DMT\BROWSER\ComboBox\URLS\NonAdult]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\DMT\BROWSER\DEFAULTS]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\DMT\BROWSER\ComboBox]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_LOCAL_MACHINE\Software\SpeedBit\Download Accelerator\ADS\SecondMedia]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_LOCAL_MACHINE\Software\SpeedBit\Download Accelerator\FileList]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\SpeedBit\DownloadAccelerator\HistoryCombo]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_LOCAL_MACHINE\SOFTWARE\SpeedBit\Download Accelerator\FileList]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Netzip\Download Demon\Version 3.0\URL History]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Netzip\Download Demon\Version 3.0\Jobs]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_USERS\.Default\Software\Netzip\Download Demon\Version 3.0\URL History]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_USERS\.Default\Software\Netzip\Download Demon\Version 3.0\Jobs]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Macromedia\Dreamweaver 3\Recent File List]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Macromedia\Dreamweaver 4\Recent File List]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\JG\EditPad\Reopen]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Firehand Technologies\Lightning\MRU]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Firehand Technologies\Firehand Lightning Photo Album Viewer\MRU]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Firehand Technologies\Firehand Lightning Slideshow Player\MRU]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Macromedia\Flash 5\Recent File List]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Applets\FreeCell]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Google\NavClient\1.1\History]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_USERS\.Default\Software\Google\NavClient\1.1\History]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [HKEY_CURRENT_USER\Software\Microsoft\Protected Storage System Provider\S-1-5-21-1757981266-1078145449-1202660629-1003\Data\e161255a-37c3-11d2-bcaa-00c04fd929db\e161255a-37c3-11d2-bcaa-00c04fd929db\q:StringData]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO "Behavior"=->> "%Temp%.\ProgMRUCleanup.reg"
ECHO "Item Data"=->> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [HKEY_CURRENT_USER\Software\Microsoft\Protected Storage System Provider\S-1-5-21-1757981266-1078145449-1202660629-1003\Data\e161255a-37c3-11d2-bcaa-00c04fd929db\e161255a-37c3-11d2-bcaa-00c04fd929db\q:StringIndex]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO "Behavior"=->> "%Temp%.\ProgMRUCleanup.reg"
ECHO "Item Data"=->> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Microsoft\FrontPad\FrontPage Editor\Recent File List]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Microsoft\FrontPage\Explorer\FrontPage Explorer\Recent File List]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Microsoft\FrontPage\Explorer\FrontPage Explorer\Recent Page List]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Microsoft\FrontPage\Explorer\FrontPage Explorer\Recent Web List]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\software\microsoft\works\4.0\recent file list]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Rhino Software\FTP Voyager\Most Recent Sites]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\HeadLight\GetRight\MRU]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\HeadLight\GetRight\TypedURLS]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Allaire\HomeSite4\RecentFiles]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Microsoft\HTML Help Workshop\Recent File List]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Adobe\ImageReady 3.0\Preferences\RecentFiles]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\software\jetcar\jetcar\recent file list]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\MMedia Research Corp\LView Pro Image Processor\Recent File List]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Orient Lab\Magic Mail Monitor\Recent File List]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Axialis\MediaBrowser\CoolBarList]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Axialis\MediaBrowser\folders]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Axialis\MediaBrowser\Recent File List]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_USERS\.DEFAULT\Software\Axialis\MediaBrowser\CoolBarList]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_USERS\.DEFAULT\Software\Axialis\MediaBrowser\folders]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_USERS\.DEFAULT\Software\Axialis\MediaBrowser\Recent File List]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Software\Impact\Microangelo\Studio\MRU List]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Impact\Microangelo\Librarian\MRU List]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Impact\Microangelo\Animator\MRU List]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [HKEY_CURRENT_USER\Software\ahead\Nero - Burning Rom\Settings]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO "ImageDir"=->> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [HKEY_LOCAL_MACHINE\SOFTWARE\Ahead\Nero - Burning Rom\Settings]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO "ImageDir"=->> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Microsoft\Office\9.0\Excel\Recent Files]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Microsoft\Office\9.0\Publisher\Recent File List]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Microsoft\FrontPage\Explorer\FrontPage Explorer\Recent Page List]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Microsoft\Conferencing\UI\CallMRU]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Microsoft\Conferencing\UI\Directory]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_USERS\.DEFAULT\Software\Microsoft\Conferencing\UI\CallMRU]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_USERS\.DEFAULT\Software\Microsoft\Conferencing\UI\Directory]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Microsoft\PhotoDraw\1.0\Recent File List]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Microsoft\Visual Basic\6.0\RecentFiles]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\VB and VBA Program Settings\Microsoft Visual Basic AddIns\VisData6]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\netants\mru]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_USERS\.default\Software\netants\mru]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Stilesoft\NetCaptor\CurrentVersion\Last Open Sites]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Caere Corp\OmniPage10.0\OMNIPAGE\Recent File List]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\JASC\Paint Shop Pro 5\Recent File List]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\JASC\Paint Shop Pro 6\Recent File List]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\JASC\Paint Shop Pro 7\Recent File List]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Ulead Systems\Ulead PhotoImpact\5.0\Recent File List]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Ulead Systems\Ulead PhotoImpact\6.0\Recent File List]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Ulead Systems\PhotoImpact Viewer\4.0\Recent File List]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Adobe\Photoshop\6.0\VisitedDirs]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Micrografx\Picture Publisher\8.0\Recent File List]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\PowerArchiver\Files\Active_File]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\PowerArchiver\Files\Extract]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\PowerArchiver\Files\SelDir]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CLASSES_ROOT\software\realnetworks\realplayer\6.0\preferences\mostrecentclips1]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CLASSES_ROOT\software\realnetworks\realplayer\6.0\preferences\mostrecentclips2]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CLASSES_ROOT\software\realnetworks\realplayer\6.0\preferences\mostrecentclips3]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CLASSES_ROOT\software\realnetworks\realplayer\6.0\preferences\mostrecentclips4]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CLASSES_ROOT\software\realnetworks\realplayer\6.0\preferences\mostrecentclips5]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CLASSES_ROOT\software\realnetworks\realplayer\6.0\preferences\mostrecentclips6]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CLASSES_ROOT\software\realnetworks\realplayer\6.0\preferences\mostrecentclips7]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CLASSES_ROOT\software\realnetworks\realplayer\6.0\preferences\mostrecentclips8]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CLASSES_ROOT\software\realnetworks\realplayer\6.0\preferences\mostrecentclips9]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CLASSES_ROOT\software\realnetworks\realplayer\6.0\preferences\mostrecentclips10]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_LOCAL_MACHINE\software\classes\software\realnetworks\realplayer\6.0\preferences\mostrecentclips1]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_LOCAL_MACHINE\software\classes\software\realnetworks\realplayer\6.0\preferences\mostrecentclips2]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_LOCAL_MACHINE\software\classes\software\realnetworks\realplayer\6.0\preferences\mostrecentclips3]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_LOCAL_MACHINE\software\classes\software\realnetworks\realplayer\6.0\preferences\mostrecentclips4]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_LOCAL_MACHINE\software\classes\software\realnetworks\realplayer\6.0\preferences\mostrecentclips5]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_LOCAL_MACHINE\software\classes\software\realnetworks\realplayer\6.0\preferences\mostrecentclips6]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_LOCAL_MACHINE\software\classes\software\realnetworks\realplayer\6.0\preferences\mostrecentclips7]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_LOCAL_MACHINE\software\classes\software\realnetworks\realplayer\6.0\preferences\mostrecentclips8]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_LOCAL_MACHINE\software\classes\software\realnetworks\realplayer\6.0\preferences\mostrecentclips9]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_LOCAL_MACHINE\software\classes\software\realnetworks\realplayer\6.0\preferences\mostrecentclips10]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CLASSES_ROOT\software\realnetworks\realplayer\6.0\preferences\openlocationclips1]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CLASSES_ROOT\software\realnetworks\realplayer\6.0\preferences\openlocationclips2]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CLASSES_ROOT\software\realnetworks\realplayer\6.0\preferences\openlocationclips3]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CLASSES_ROOT\software\realnetworks\realplayer\6.0\preferences\openlocationclips4]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CLASSES_ROOT\software\realnetworks\realplayer\6.0\preferences\openlocationclips5]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CLASSES_ROOT\software\realnetworks\realplayer\6.0\preferences\openlocationclips6]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CLASSES_ROOT\software\realnetworks\realplayer\6.0\preferences\openlocationclips7]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CLASSES_ROOT\software\realnetworks\realplayer\6.0\preferences\openlocationclips8]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CLASSES_ROOT\software\realnetworks\realplayer\6.0\preferences\openlocationclips9]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CLASSES_ROOT\software\realnetworks\realplayer\6.0\preferences\openlocationclips10]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_LOCAL_MACHINE\software\classes\realnetworks\realplayer\6.0\preferences\openlocationclips1]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_LOCAL_MACHINE\software\classes\software\realnetworks\realplayer\6.0\preferences\openlocationclips2]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_LOCAL_MACHINE\software\classes\software\realnetworks\realplayer\6.0\preferences\openlocationclips3]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_LOCAL_MACHINE\software\classes\software\realnetworks\realplayer\6.0\preferences\openlocationclips4]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_LOCAL_MACHINE\software\classes\software\realnetworks\realplayer\6.0\preferences\openlocationclips5]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_LOCAL_MACHINE\software\classes\software\realnetworks\realplayer\6.0\preferences\openlocationclips6]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_LOCAL_MACHINE\software\classes\software\realnetworks\realplayer\6.0\preferences\openlocationclips7]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_LOCAL_MACHINE\software\classes\software\realnetworks\realplayer\6.0\preferences\openlocationclips8]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_LOCAL_MACHINE\software\classes\software\realnetworks\realplayer\6.0\preferences\openlocationclips9]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_LOCAL_MACHINE\software\classes\software\realnetworks\realplayer\6.0\preferences\openlocationclips10]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CLASSES_ROOT\Software\RealNetworks\RealPlayer\6.0\Preferences\HistoryList\URL1]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CLASSES_ROOT\Software\RealNetworks\RealPlayer\6.0\Preferences\LastOpenFileDir]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\RealNetworks\RealDownload\4.0\URL History]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\RealNetworks\RealDownload\4.0\Jobs]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_LOCAL_MACHINE\.default\Software\RealNetworks\RealDownload\4.0\Jobs]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CLASSES_ROOT\Software\RealNetworks\RealPlayer\6.0\Preferences\NumMostRecentClips]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CLASSES_ROOT\Software\RealNetworks\RealPlayer\6.0\Preferences\MostRecentClips]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Scour\Scour Exchange\Hotlist]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_USERS\.default\Software\Scour\Scour Exchange\Hotlist]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Sonic Foundry\ACID\2.0\Metrics]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_USERS\.DEFAULT\Software\Sonic Foundry\ACID\2.0\Metrics]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_USERS\.DEFAULT\Software\Sonic Foundry\ACID\2.0\Metrics\MRU Folders]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_USERS\.DEFAULT\Software\Sonic Foundry\ACID\2.0\Metrics\Kernel]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\software\mediascience\sonique\play_history]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\software\mediascience\sonique\url_history]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Tennyson Maxwell\Teleport Pro\Recent File List]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_USERS\.default\Software\Tennyson Maxwell\Teleport Pro\Recent File List]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Helios\TextPad 3\Recent File List]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Helios\TextPad 3\Recent Strings]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Helios\TextPad 4\Recent File List]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Helios\TextPad 4\Recent Strings]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\UltraPlayer\MRU]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_USERS\.default\software\megalux\UP\MRU Items]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_USERS\.default\software\megalux\UP\OF tems]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\software\megalux\UP\MRU Items]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\software\megalux\UP\OF Items]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Ulead Systems\Ulead Photo Express\2.0\ULEAD32.INI\RecentFile]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Visio\Visio 2000\application]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\e-merge\WinAce\2.0\MRU Items]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\software\e-merge\winace\1.0\favorites]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\software\e-merge\winace\1.0\mru items]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\software\e-merge\winace\1.0\copy]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\WinRAR\ArcHistory]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\WinRAR\DialogEditHistory\ArcName]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\WinRAR\DialogEditHistory\ExtrPath]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\WinRAR\ArcHistory]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\WinRAR\DialogEditHistory]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_USERS\.DEFAULT\Software\WinRAR\ArcHistory]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_USERS\.DEFAULT\Software\WinRAR\DialogEditHistory]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Nico Mak Computing\WinZip\filemenu]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Nico Mak Computing\WinZip\extract]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_USERS\.DEFAULT\Software\Nico Mak Computing\WinZip\filemenu]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_USERS\.DEFAULT\Software\Nico Mak Computing\WinZip\extract]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Xara\X3D4\Recent File List]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Yahoo\YPlayer\Recent URLs]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\YAMAHA\XGplayer\Recent File List]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"
ECHO [-HKEY_CURRENT_USER\Software\Mijenix\ZipMagic\CurrentVersion\Recent]>> "%Temp%.\ProgMRUCleanup.reg"
ECHO.>> "%Temp%.\ProgMRUCleanup.reg"

REGEDIT.EXE /S "%Temp%.\ProgMRUCleanup.reg"

DEL "%Temp%.\ProgMRUCleanup.reg"